const state={data:null,links:[],hotels:[],hotelNotice:'',map:null,selectedDayIndex:0};
const routeStops=[
  {name:'Snekkersten',lat:56.0095,lng:12.5822,type:'day'},{name:'København Syd',lat:55.6380,lng:12.5360,type:'night'},{name:'Berlin Hbf',lat:52.5251,lng:13.3694,type:'day'},{name:'Kraków Główny',lat:50.0674,lng:19.9472,type:'night'},{name:'Wien Hbf',lat:48.1852,lng:16.3768,type:'day'},{name:'Innsbruck Hbf',lat:47.2639,lng:11.4010,type:'day'},{name:'Chur',lat:46.8530,lng:9.5308,type:'panorama'},{name:'St. Moritz',lat:46.4970,lng:9.8380,type:'panorama'},{name:'Tirano',lat:46.2165,lng:10.1690,type:'day'},{name:'Milano Centrale',lat:45.4856,lng:9.2042,type:'day'},{name:'Montreux',lat:46.4358,lng:6.9107,type:'panorama'},{name:'Interlaken Ost',lat:46.6900,lng:7.8690,type:'day'},{name:'Antwerpen-Centraal',lat:51.2172,lng:4.4211,type:'day'},{name:'Bruxelles-Midi',lat:50.8357,lng:4.3365,type:'night'},{name:'Hamburg-Harburg',lat:53.4568,lng:9.9917,type:'day'},{name:'København H',lat:55.6727,lng:12.5649,type:'day'},{name:'Snekkersten',lat:56.0095,lng:12.5822,type:'day'}
];
const colors={day:'#25835b',night:'#173a7a',panorama:'#ef8d22'};
const operatorLinks={
  rejseplanen:{label:'Rejseplanen',url:'https://www.rejseplanen.dk/'},snalltaget:{label:'Snälltåget',url:'https://www.snalltaget.se/en/berlin'},db:{label:'Deutsche Bahn',url:'https://int.bahn.de/en'},pkp:{label:'PKP Intercity',url:'https://www.intercity.pl/en/'},oebb:{label:'ÖBB',url:'https://www.oebb.at/en/'},nightjet:{label:'Nightjet / EuroNight',url:'https://www.nightjet.com/en/'},sbb:{label:'SBB',url:'https://www.sbb.ch/en'},rhb:{label:'Rhätische Bahn',url:'https://www.rhb.ch/en/'},bernina:{label:'Bernina Express',url:'https://www.rhb.ch/en/panoramic-journeys/bernina-express/'},trenord:{label:'Trenord',url:'https://www.trenord.it/en/'},goldenpass:{label:'GoldenPass Express',url:'https://www.gpx.swiss/en/'},belgian:{label:'Belgian Train',url:'https://www.belgiantrain.be/en'},europeanSleeper:{label:'European Sleeper',url:'https://www.europeansleeper.eu/timetable'}
};

async function loadData(){
  try{
    const [tripRes,linksRes,hotelsRes]=await Promise.all([fetch('data/itinerary.json'),fetch('data/links.json'),fetch('data/hotels.json')]);
    if(!tripRes.ok||!linksRes.ok||!hotelsRes.ok)throw new Error('Data kunne ikke hentes');
    state.data=await tripRes.json();state.links=await linksRes.json();
    const hotelData=await hotelsRes.json();state.hotels=hotelData.hotels||[];state.hotelNotice=hotelData.notice||'';
    state.selectedDayIndex=getCurrentDayIndex();initApp();
  }catch(error){console.error(error);document.querySelector('main').innerHTML='<article class="about-card"><h2>Appdata kunne ikke indlæses</h2><p>Genindlæs siden. Første åbning kræver internet, hvorefter appen kan bruges offline.</p></article>';}
}
function initApp(){bindNavigation();bindTheme();bindDayNavigation();renderOverview();renderDayChooser();renderSelectedDay();renderFullTrip();renderLinks();registerServiceWorker();}
function bindNavigation(){document.querySelectorAll('[data-nav]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.nav)));}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='route')setTimeout(renderMap,80);if(id==='today')renderSelectedDay();}
function bindTheme(){const saved=localStorage.getItem('interrail-theme');if(saved==='dark')document.body.classList.add('dark');updateThemeIcon();document.getElementById('themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('interrail-theme',document.body.classList.contains('dark')?'dark':'light');updateThemeIcon();});}
function updateThemeIcon(){document.getElementById('themeToggle').textContent=document.body.classList.contains('dark')?'☀':'☾'}
function localDate(value){return new Date(`${value}T12:00:00`)}
function formatDate(value){return new Intl.DateTimeFormat('da-DK',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(localDate(value))}
function shortDate(value){return new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'short'}).format(localDate(value))}
function getCurrentDayIndex(){const now=new Date(),days=state.data.days;const exact=days.findIndex(d=>d.date===now.toISOString().slice(0,10));if(exact>=0)return exact;if(now<localDate(days[0].date))return 0;const past=[...days].map((day,index)=>({day,index})).reverse().find(item=>now>=localDate(item.day.date));return past?.index??0;}
function getProgress(){const start=localDate(state.data.trip.start),end=localDate(state.data.trip.end),now=new Date();if(now<=start)return 0;if(now>=end)return 100;return Math.round(((now-start)/(end-start))*100);}
function renderOverview(){const day=state.data.days[getCurrentDayIndex()];document.getElementById('nextTitle').textContent=day.title;document.getElementById('nextDate').textContent=formatDate(day.date);const diff=localDate(state.data.trip.start)-new Date(),count=document.getElementById('countdown');if(diff>0){const n=Math.ceil(diff/86400000);count.textContent=`${n} ${n===1?'dag':'dage'} til afrejse`;}else if(new Date()<=localDate(state.data.trip.end)){count.textContent='Rejsen er i gang';}else count.textContent='Rejsen er afsluttet';const p=getProgress();document.getElementById('progressText').textContent=`${p} %`;document.getElementById('progressBar').style.width=`${p}%`;}
function renderDayChooser(){const container=document.getElementById('dayChooser');container.innerHTML=state.data.days.map((day,index)=>`<button class="day-choice ${index===getCurrentDayIndex()?'is-current':''}" type="button" data-day-index="${index}"><span class="day-choice-number">Dag ${index+1}</span><strong>${escapeHtml(day.title)}</strong><small>${escapeHtml(shortDate(day.date))}</small></button>`).join('');container.querySelectorAll('[data-day-index]').forEach(button=>button.addEventListener('click',()=>selectDay(Number(button.dataset.dayIndex))));}
function selectDay(index){state.selectedDayIndex=Math.max(0,Math.min(index,state.data.days.length-1));renderSelectedDay();showView('today');}
function bindDayNavigation(){document.getElementById('previousDay').addEventListener('click',()=>selectDay(state.selectedDayIndex-1));document.getElementById('nextDay').addEventListener('click',()=>selectDay(state.selectedDayIndex+1));}
function getEventLinks(event){const text=`${event.title} ${event.detail}`.toLowerCase(),links=[];const add=key=>{if(!links.some(item=>item.url===operatorLinks[key].url))links.push(operatorLinks[key]);};if(/snekkersten|københavn|dsb|kystban/.test(text))add('rejseplanen');if(/snälltåget/.test(text))add('snalltaget');if(/berlin|deutsche bahn|\bdb\b/.test(text))add('db');if(/kraków|polsk|pkp|eurocity/.test(text))add('pkp');if(/wien|innsbruck|railjet|öbb/.test(text))add('oebb');if(/euronight|nightjet|sovekupé/.test(text))add('nightjet');if(/chur|interlaken|basel|simplon|sbb|schweiz/.test(text))add('sbb');if(/albula|rhätische|rhb/.test(text))add('rhb');if(/bernina/.test(text))add('bernina');if(/tirano|trenord|milano/.test(text))add('trenord');if(/goldenpass|montreux/.test(text))add('goldenpass');if(/antwerpen|belgisk ic|bruxelles-midi/.test(text))add('belgian');if(/european sleeper|hamburg-harburg/.test(text))add('europeanSleeper');return links.slice(0,2);}
function eventLinksHtml(event){const links=getEventLinks(event);return links.length?`<div class="departure-links">${links.map(link=>`<a href="${link.url}" target="_blank" rel="noopener noreferrer">Opdatering hos ${escapeHtml(link.label)} ↗</a>`).join('')}</div>`:'';}
function hotelForDate(date){return state.hotels.find(h=>date>=h.checkInDate&&date<h.checkOutDate)||null;}
function hotelValue(value,fallback='Afventer hotelvalg'){return value?escapeHtml(value):fallback;}
function hotelLinks(hotel){const links=[];if(hotel.mapUrl)links.push(`<a href="${escapeHtml(hotel.mapUrl)}" target="_blank" rel="noopener noreferrer">Åbn i kort ↗</a>`);else if(hotel.address)links.push(`<a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(hotel.address)}" target="_blank" rel="noopener noreferrer">Find adressen ↗</a>`);if(hotel.website)links.push(`<a href="${escapeHtml(hotel.website)}" target="_blank" rel="noopener noreferrer">Hotellets hjemmeside ↗</a>`);if(hotel.phone)links.push(`<a href="tel:${escapeHtml(hotel.phone)}">Ring til hotellet</a>`);return links.length?`<div class="hotel-links">${links.join('')}</div>`:'';}
function renderHotel(day){const box=document.getElementById('hotelDetails'),hotel=hotelForDate(day.date);if(!hotel){box.innerHTML='';return;}const isPending=!hotel.name;box.innerHTML=`<article class="hotel-card ${isPending?'is-pending':''}"><div class="hotel-title"><span>🏨</span><div><p class="section-kicker">OVERNATNING</p><h3>${hotelValue(hotel.name,`Hotel i ${escapeHtml(hotel.city)} afventer`)}</h3></div></div><div class="hotel-grid"><div><small>Adresse</small><strong>${hotelValue(hotel.address)}</strong></div><div><small>Check-in</small><strong>${hotelValue(hotel.checkInTime,'Tidspunkt afventer')}</strong></div><div><small>Check-out</small><strong>${hotelValue(hotel.checkOutTime,'Tidspunkt afventer')}</strong></div><div><small>Bookingnummer</small><strong>${hotelValue(hotel.bookingReference,'Afventer reservation')}</strong></div></div>${hotel.notes?`<p class="hotel-note">${escapeHtml(hotel.notes)}</p>`:''}${hotelLinks(hotel)}${isPending?`<p class="hotel-pending">Klar til hotelnavn, adresse, check-in, check-out, bookingnummer, telefon, hjemmeside og noter.</p>`:''}</article>`;}
function renderSelectedDay(){const day=state.data.days[state.selectedDayIndex];document.getElementById('dayNumber').textContent=`DAG ${state.selectedDayIndex+1} AF ${state.data.days.length}`;document.getElementById('todayDate').textContent=formatDate(day.date);document.getElementById('todayCard').innerHTML=`<article class="trip-card"><span class="badge">${escapeHtml(day.status)}</span><div class="route">${escapeHtml(day.title)}</div><p>${escapeHtml(day.summary)}</p><small><strong>Overnatning:</strong> ${escapeHtml(day.overnight)}</small></article>`;renderHotel(day);document.getElementById('timeline').innerHTML=day.events.map(event=>`<div class="timeline-item"><div class="timeline-time">${escapeHtml(event.time)}</div><div class="timeline-dot"></div><div class="timeline-body"><strong>${escapeHtml(event.title)}</strong><p>${escapeHtml(event.detail)}</p>${eventLinksHtml(event)}</div></div>`).join('');document.getElementById('previousDay').disabled=state.selectedDayIndex===0;document.getElementById('nextDay').disabled=state.selectedDayIndex===state.data.days.length-1;}
function renderFullTrip(){document.getElementById('fullTripList').innerHTML=state.data.days.map((day,index)=>`<button class="full-trip-day" type="button" data-full-day="${index}"><span class="full-trip-day-number">${index+1}</span><span class="full-trip-day-copy"><small>${escapeHtml(shortDate(day.date))} · ${escapeHtml(day.status)}</small><strong>${escapeHtml(day.title)}</strong><span>${escapeHtml(day.summary)}</span></span><b>→</b></button>`).join('');document.querySelectorAll('[data-full-day]').forEach(button=>button.addEventListener('click',()=>selectDay(Number(button.dataset.fullDay))));}
function renderLinks(){document.getElementById('linkList').innerHTML=state.links.map(link=>`<a class="link-card" href="${link.url}" target="_blank" rel="noopener noreferrer"><div><strong>${escapeHtml(link.title)}</strong><small>${escapeHtml(link.subtitle)}</small></div><b>${link.icon}</b></a>`).join('');}
function renderMap(){if(state.map){state.map.invalidateSize();return;}state.map=L.map('map',{zoomControl:true}).setView([49,10],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap-bidragsydere'}).addTo(state.map);routeStops.forEach((stop,index)=>{L.circleMarker([stop.lat,stop.lng],{radius:7,color:'#fff',weight:2,fillColor:colors[stop.type],fillOpacity:1}).addTo(state.map).bindPopup(`<strong>${index+1}. ${stop.name}</strong>`);if(index<routeStops.length-1){const next=routeStops[index+1];L.polyline([[stop.lat,stop.lng],[next.lat,next.lng]],{color:colors[stop.type],weight:5,opacity:.85}).addTo(state.map);}});state.map.fitBounds(routeStops.map(s=>[s.lat,s.lng]),{padding:[24,24]});}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function registerServiceWorker(){if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(console.error)}
loadData();